services:
  autogen-server:
    build: ./autogen_gis
    ports:
      - 8002:8000
    env_file: .env
    environment:
      - IS_DOCKER_CONTAINER=true
    develop:
      watch:
        - action: rebuild
          path: ./autogen_gis
  open-interpreter-server:
    build: ./backend
    ports:
      - 8001:8000
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: ./backend
  # solidjs-client:
  #   build: ./frontend
  #   ports:
  #     - 3001:5173
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./frontend
