version: '3'

services:
  postgis-db:
    build: ./postgres
    # image: postgis/postgis:16-3.4
    ports:
      - 5433:5432
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: geogpt_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgis-db-osm:
    build: ./postgres
    # image: postgis/postgis:16-3.4
    ports:
      - 5434:5432
    command: postgres -c listen_addresses='*'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: geogpt_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data-osm:/var/lib/postgresql/data

  ogc-api-features-server:
    image: pramsey/pg_featureserv
    ports:
      - 9000:9000
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgis-db/geogpt_db
      - DEBUG=true
      - DEVEL=true
      - PGFS_PAGING_LIMITMAX=10000
    depends_on:
      - postgis-db

  ogc-api-features-server-osm:
    image: pramsey/pg_featureserv
    ports:
      - 9001:9000
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgis-db-osm/geogpt_db
      - DEBUG=true
      - DEVEL=true
      - PGFS_PAGING_LIMITMAX=10000
    depends_on:
      - postgis-db-osm

  redis-db:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  # langchain-server:
  #   build: ./langchain
  #   ports:
  #     - 8003:8000
  #   env_file: .env
  #   environment:
  #     - IS_DOCKER_CONTAINER=true
  #     - REDIS_URL=redis://redis-db:6379
  #   depends_on:
  #     - redis-db
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./langchain

  # solidjs-client:
  #   build: ./frontend
  #   ports:
  #     - 3001:5173
  #   env_file: .env
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./frontend

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  postgres-data-osm:
    driver: local
