services:
  # autogen-server:
  #   build: ./autogen_gis
  #   ports:
  #     - 8002:8000
  #   env_file: .env
  #   environment:
  #     - IS_DOCKER_CONTAINER=true
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./autogen_gis
  # open-interpreter-server:
  #   build: ./backend
  #   ports:
  #     - 8001:8000
  #   env_file: .env
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./backend
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    # volumes:
    #   - redis_data:/data

  langchain-server:
    build: ./langchain
    ports:
      - 8003:8000
    env_file: .env
    environment:
      - IS_DOCKER_CONTAINER=true
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    develop:
      watch:
        - action: rebuild
          path: ./langchain

  solidjs-client:
    build: ./frontend
    ports:
      - 3001:5173
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: ./frontend
# volumes:
#   redis_data:
